name: spopt
channels:
  - conda-forge
dependencies: 
  - python=3.10
  - geopandas>=0.12.0
  - jupyterlab
  - libpysal
  - mapclassify
  - networkx
  - numpy>=1.21
  - pandas>=1.0.5
  - pip
  - pulp
  - scikit-learn>=0.22
  - scipy>=1.3.2
  - shapely>=2.0
  - tqdm>=4.27.0
  - pointpats
  
  # notebook/binder specific
  - folium
  - glpk
  - inequality
  - matplotlib
  - matplotlib-scalebar
  - overpy
  - seaborn
  - spaghetti
  - watermark
  
  # bleeding edge spopt
  - pip:
    - git+https://github.com/pysal/spopt.git@main
    # (notebook/binder specific) having trouble resolving routingpy via conda-forge
    - routingpy
    - pulp
