name: spopt
channels:
  - conda-forge
dependencies: 
  - python=3.9
  - descartes
  - geopandas>=0.7.0
  - jupyterlab
  - libpysal
  - mapclassify
  - matplotlib
  - networkx
  - numpy>=1.3
  - pandas>=1
  - pulp
  - scikit-learn>=0.22
  - scipy>=1.0
  - spaghetti
  - watermark
