name: spopt
channels:
  - conda-forge
dependencies: 
  - python=3.10
  - geopandas>=0.7.0
  - jupyterlab
  - libpysal
  - mapclassify
  - networkx
  - numpy>=1.3
  - pandas>=1
  - pip
  #- pulp ##############################
  - scikit-learn>=0.22
  - scipy>=1.0
  
  # notebook/binder specific
  - folium
  - glpk
  - inequality
  - matplotlib
  - matplotlib-scalebar
  - overpy
  - routingpy
  - seaborn
  - spaghetti
  - watermark
  
  # bleeding edge spopt
  - pip:
    - git+https://github.com/pysal/spopt.git@main
    # (notebook/binder specific) having trouble resolving routingpy via conda-forge
    #- routingpy
    - pulp
