# See https://github.com/python-versioneer/python-versioneer
name: "Update Versioneer"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Manual Versioneer Run
        default: test
        required: false
  schedule:
    - cron: "0 6 1 * *" # 1st day of each month at 06:00 UTC
  push:
    paths:
      - "setup.cfg"
      - ".github/workflows/versioneer.yml"

jobs:
  versioneer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install and run versioneer
        run: |
          pip install versioneer[toml]
          versioneer install
      - name: Blacken code
        uses: psf/black@stable
        with:
          options: "--verbose"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: versioneer.py
      - name: Ignore changes in __init__
        run: |
          git reset -- spopt/__init__.py
          git checkout -- spopt/__init__.py
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update Versioneer"
          branch: update-versioneer
          base: main
          commit-message: "[Bot] Update Versioneer"

          body: |
            Automatic update of Versioneer by the `versioneer.yml` workflow.
